services:
  - type: web
    name: comp5048-air-quality
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
